server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    simpleQueue: simple.queue
    routingkey: user.routingkey
    simpleRoutingkey: simple.routingkey